name: Check SimS codebase

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions: {}

env:
  RUSTFLAGS: -Dwarnings

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Check code format
        run: cargo fmt --check
      - name: Check code
        run: cargo check
      - name: Code linting
        run: cargo clippy --all-features --tests --benches
      - name: Build
        run: cargo build --all-features
      - name: Unit tests
        run: cargo test --all-features
      - name: Doc
        run: cargo doc
