name: Release SimS

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  check:
    name: Check
    uses: ./.github/workflows/ci.yml

  release:
    name: Release
    needs: check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Check that the tag matches the crate version
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/v}
          CARGO_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "sims") | .version')
          [[ "${RELEASE_VERSION}" == "${CARGO_VERSION}" ]] || (echo "The tag version does not match the one in Cargo.toml" && false)
      - name: Create the release
        uses: ncipollo/release-action@v1
      - name: Publish the crate
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
